#!/bin/sh
	[ -d $D/usr/bin/cam ] || mkdir $D/usr/bin/cam
	[ -d $D/var/emu ] || mkdir $D/var/emu
	[ -d $D/var/keys ] || ln -s $D/usr/keys $D/var/keys
	[ -f $D/usr/keys/newcamd.list ] || mv $D/usr/keys/newcamd.list_Example $D/usr/keys/newcamd.list
	[ -f $D/usr/keys/mg_cfg ] || mv $D/usr/keys/mg_cfg_Example $D/usr/keys/mg_cfg
	[ -f $D/usr/keys/ignore.list ] || mv $D/usr/keys/ignore.list_Example $D/usr/keys/ignore.list
	[ -f $D/usr/keys/priority.list ] || mv $D/usr/keys/priority.list_Example $D/usr/keys/priority.list
	[ -f $D/usr/keys/replace.list ] || mv $D/usr/keys/replace.list_Example $D/usr/keys/replace.list
	[ -f $D/usr/keys/SoftCam.Key ] || mv $D/usr/keys/SoftCam.Key_ExampleM $D/usr/keys/SoftCam.Key
	[ -f $D/usr/keys/AutoRoll.Key ] || mv $D/usr/keys/AutoRoll.Key_Example $D/usr/keys/AutoRoll.Key
	ln -s $D/usr/bin/mgcamd $D/usr/bin/cam/mgcamd
	ln -s $D/usr/bin/mgcamd $D/var/emu/mgcamd
# Следующие строки закомментированы в связи с необходимостью отмены автозапуска MgCamd
# при его установке (так как неизвестно что именно будет использоваться в качестве менеджера эмуляторов.
#	if [ ! -e /etc/init.d/softcam ] || [ "$D/etc/init.d/softcam.None" == `readlink -f $D/etc/init.d/softcam` ]
#	then
#		rm -f $D/etc/init.d/softcam
#		ln -s softcam.mgcamd $D/etc/init.d/softcam
#		echo "Switching default softcam to mgcamd"
#	fi
#	if [ "/etc/init.d/softcam.mgcamd" == `readlink -f /etc/init.d/softcam` ]
#	then
#		echo "Softcam is selected as default, (re)starting mgcamd"
#		/etc/init.d/softcam.mgcamd restart
#	fi
exit 0
