#!/bin/sh
echo ""
echo "**************************************************************"
echo "*  Softcam setup mod for openPLi                             *"
echo "*  Coded Dima73 (c) 2012                                     *"
echo "**************************************************************"
echo ""
echo "Plugin successfully installed! You should restart enigma2 now!"
echo ""
exit 0
