#!/bin/sh
	[ -d $D/usr/bin/cam ] || mkdir $D/usr/bin/cam
	[ -d $D/var/emu ] || mkdir $D/var/emu
	[ -d $D/var/keys ] || ln -s $D/usr/keys $D/var/keys
	[ -d $D/etc/tuxbox/config/oscam.ac ] || mv $D/etc/tuxbox/config/oscam.ac_ $D/etc/tuxbox/config/oscam.ac
	[ -d $D/etc/tuxbox/config/oscam.cacheex ] || mv $D/etc/tuxbox/config/oscam.cacheex_ $D/etc/tuxbox/config/oscam.cacheex
	[ -d $D/etc/tuxbox/config/oscam.cert ] || mv $D/etc/tuxbox/config/oscam.cert_ $D/etc/tuxbox/config/oscam.cert
	[ -d $D/etc/tuxbox/config/oscam.conf ] || mv $D/etc/tuxbox/config/oscam.conf_ $D/etc/tuxbox/config/oscam.conf
	[ -d $D/etc/tuxbox/config/oscam.dvbapi ] || mv $D/etc/tuxbox/config/oscam.dvbapi_ $D/etc/tuxbox/config/oscam.dvbapi
	[ -d $D/etc/tuxbox/config/oscam.guess ] || mv $D/etc/tuxbox/config/oscam.guess_ $D/etc/tuxbox/config/oscam.guess
	[ -d $D/etc/tuxbox/config/oscam.ird ] || mv $D/etc/tuxbox/config/oscam.ird_ $D/etc/tuxbox/config/oscam.ird
	[ -d $D/etc/tuxbox/config/oscam.pem ] || mv $D/etc/tuxbox/config/oscam.pem_ $D/etc/tuxbox/config/oscam.pem
	[ -d $D/etc/tuxbox/config/oscam.provid ] || mv $D/etc/tuxbox/config/oscam.provid_ $D/etc/tuxbox/config/oscam.provid
	[ -d $D/etc/tuxbox/config/oscam.server ] || mv $D/etc/tuxbox/config/oscam.server_ $D/etc/tuxbox/config/oscam.server
	[ -d $D/etc/tuxbox/config/oscam.services ] || mv $D/etc/tuxbox/config/oscam.services_ $D/etc/tuxbox/config/oscam.services
	[ -d $D/etc/tuxbox/config/oscam.srvid ] || mv $D/etc/tuxbox/config/oscam.srvid_ $D/etc/tuxbox/config/oscam.srvid
	[ -d $D/etc/tuxbox/config/oscam.tiers ] || mv $D/etc/tuxbox/config/oscam.tiers_ $D/etc/tuxbox/config/oscam.tiers
	[ -d $D/etc/tuxbox/config/oscam.user ] || mv $D/etc/tuxbox/config/oscam.user_ $D/etc/tuxbox/config/oscam.user
	[ -d $D/etc/tuxbox/config/oscam.whitelist ] || mv $D/etc/tuxbox/config/oscam.whitelist_ $D/etc/tuxbox/config/oscam.whitelist
	[ -d $D/usr/keys/SoftCam.Key ] || mv $D/usr/keys/SoftCam.Key_Oscam $D/usr/keys/SoftCam.Key
	ln -s $D/usr/bin/oscam $D/usr/bin/cam/oscam
	ln -s $D/usr/bin/oscam $D/var/emu/oscam
# Следующие строки закомментированы в связи с необходимостью отмены автозапуска Wicardd
# при его установке (так как неизвестно что именно будет использоваться в качестве менеджера эмуляторов.
#	if [ ! -e /etc/init.d/cardserver ] || [ "$D/etc/init.d/cardserver.None" == `readlink -f $D/etc/init.d/cardserver` ]
#	then
#		rm -f $D/etc/init.d/cardserver
#		ln -s cardserver.oscam $D/etc/init.d/cardserver
#		echo "Switching default cardserver to oscam"
#	fi
#	if [ "/etc/init.d/cardserver.oscam" == `readlink -f /etc/init.d/cardserver` ]
#	then
#		echo "Cardserver is selected as default, (re)starting oscam"
#		/etc/init.d/cardserver.oscam restart
#	fi
exit 0
