#!/bin/sh
echo ""
echo ""
rm -rf /usr/lib/enigma2/python/Components/ServiceList.py
cp /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ServiceList-ori.py /usr/lib/enigma2/python/Components/ServiceList-ori.py
cp /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ServiceList.py /usr/lib/enigma2/python/Components/ServiceList.py
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ServiceList-ori.py
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ServiceList.py
rm -rf /usr/lib/enigma2/python/Screens/ChannelSelection.py
cp /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ChannelSelection-ori.py /usr/lib/enigma2/python/Screens/ChannelSelection-ori.py
cp /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ChannelSelection.py /usr/lib/enigma2/python/Screens/ChannelSelection.py
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ChannelSelection-ori.py
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/ChannelSelection.py
rm -rf /usr/lib/enigma2/python/Components/EpgList.py
cp /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/EpgList-ori.py /usr/lib/enigma2/python/Components/EpgList-ori.py
cp /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/EpgList.py /usr/lib/enigma2/python/Components/EpgList.py
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/EpgList-ori.py
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/ExtraChannelSelection/EpgList.py
echo ""
echo ""
echo "Plugin successfully installed! You should restart enigma2 now!"
echo ""
echo ""
exit 0
