#!/bin/sh
echo ""
echo ""
echo "Restoring original components"
cp /usr/lib/enigma2/python/Components/ServiceList-ori.py /usr/lib/enigma2/python/Components/ServiceList.py
rm -rf /usr/lib/enigma2/python/Components/ServiceList-ori.py
cp /usr/share/enigma2/keymap-ori.xml /usr/share/enigma2/keymap.xml
rm -rf /usr/share/enigma2/keymap-ori.xml
cp /usr/lib/enigma2/python/Screens/ChannelSelection-ori.py /usr/lib/enigma2/python/Screens/ChannelSelection.py
rm -rf /usr/lib/enigma2/python/Screens/ChannelSelection-ori.py
cp /usr/lib/enigma2/python/Components/EpgList-ori.py /usr/lib/enigma2/python/Components/EpgList.py
rm -rf /usr/lib/enigma2/python/Components/EpgList-ori.py
echo ""
echo ""
echo ""
echo "GUI will restart now!"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
init 4
sed -i '/ExtraChannelSelection/d' /etc/enigma2/settings
init 3
exit 0
