#!/bin/sh
	[ -d $D/usr/bin/cam ] || mkdir $D/usr/bin/cam
	[ -d $D/var/emu ] || mkdir $D/var/emu
	[ -d $D/var/keys ] || ln -s $D/usr/keys $D/var/keys
	[ -f $D/etc/tuxbox/config/wicardd.conf ] || cp $D/etc/tuxbox/config/wicardd.example $D/etc/tuxbox/config/wicardd.conf
	[ -f $D/usr/keys/SoftCam.Key ] || cp $D/usr/keys/SoftCam.Key_Example $D/usr/keys/SoftCam.Key
	ln -s $D/usr/bin/wicardd $D/usr/bin/cam/wicardd
	ln -s $D/usr/bin/wicardd $D/var/emu/wicardd
	ln -s $D/etc/tuxbox/config/wicardd.conf $D/var/keys/wicardd.conf
# Следующие строки закомментированы в связи с необходимостью отмены автозапуска Wicardd
# при его установке (так как неизвестно что именно будет использоваться в качестве менеджера эмуляторов.
#	if [ ! -e /etc/init.d/cardserver ] || [ "$D/etc/init.d/cardserver.None" == `readlink -f $D/etc/init.d/cardserver` ]
#	then
#		rm -f $D/etc/init.d/cardserver
#		ln -s cardserver.wicardd $D/etc/init.d/cardserver
#		echo "Switching default cardserver to wicardd"
#	fi
#	if [ "/etc/init.d/cardserver.wicardd" == `readlink -f /etc/init.d/cardserver` ]
#	then
#		echo "Cardserver is selected as default, (re)starting wicardd"
#		/etc/init.d/cardserver.wicardd restart
#	fi
exit 0
