#!/bin/sh
/etc/init.d/cardserver.wicardd stop
OLDLINK=`readlink -f /etc/init.d/cardserver`
if [ "${OLDLINK}" == "/etc/init.d/cardserver.wicardd" ]
then
	echo "wicardd was selected, now selecting None as cardserver"
	rm -f /etc/init.d/cardserver
	ln -s cardserver.None /etc/init.d/cardserver
	rm /usr/bin/cam/wicardd
	rm /var/emu/wicardd
fi
exit 0
